[package]
authors = ["kkiyama117 <kkiyama117>"]
edition = "2018"
name    = "denops-builder"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cargo      = "0.45.0"
getopts = "0.2"
